Metrics/LineLength:
  Enabled: true
  Max: 100
  AllowURI: true
  URISchemes:
    - http
    - https

Metrics/ClassLength:
  Enable: true
  Max: 200
  CountComments: false

Metrics/MethodLength:
  Enabled: true
  Max: 20
  CountComments: false

Style/AsciiComments:
  Enabled: false
