### GENERAL PLUGINS
[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
let g:indent_guides_auto_colors = 1
let g:indent_guides_enable_on_vim_startup = 1
let g:indent_guides_guide_size = 1
'''

[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
hook_add = '''
let g:asyncomplete_auto_completeopt = 0
let g:asyncomplete_popup_delay = 200
'''

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = '''
let g:lsp_diagnostics_echo_cursor = 1
let g:lsp_document_code_action_signs_enabled = 0
let g:lsp_settings_filetyple_go = ['gopls', 'golangci-lint-langserver']
'''

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
lazy = 1
hook_source = '''
let g:deoplete#auto_complete_start_length = 3
let g:deoplete#enable_at_startup = 1
let g:deoplete#enable_fuzzy_completion = 0
let g:deoplete#enable_smart_case = 1
'''

[[plugins]]
repo = 'tpope/vim-fugitive'


### LANGUAGE SPECIFIC PLUGINS
[[plugins]]
repo = 'cespare/vim-toml'
lazy = 1
on_ft = ['toml']

[[plugins]]
repo = 'mattn/vim-goimports'
lazy = 1
on_ft = ['go']

[[plugins]]
repo = 'rust-lang/rust.vim'
lazy = 1
on_ft = ['rust']

[[plugins]]
repo = 'racer-rust/vim-racer'
lazy = 1
on_ft = ['rust']

[[plugins]]
repo = 'vim-jp/cpp-vim'
lazy = 1
on_ft = ['cpp']

[[plugins]]
repo = 'vim-ruby/vim-ruby'
lazy = 1
on_ft = ['ruby']
